spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

# default: not needed but showing for completeness
eureka:
  client:
    # Try 5 times to connect before giving up
    eureka-service-url-poll-interval-seconds: 5
    fetch-registry: true
    serviceUrl:
      # Use the SERVICE NAME from your docker-compose file
      defaultZone: http://service-registry:8762/eureka/
  instance:
    # Highly recommended for Docker environments
    prefer-ip-address: true