spring:
  application:
    name: auth-service
  datasource:
    url: "jdbc:h2:mem:authDb;INIT=RUNSCRIPT FROM 'classpath:schema-h2.sql'"
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply@valaiangadi.com
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# default: not needed but showing for completeness
eureka:
  client:
    # Try 5 times to connect before giving up
    eureka-service-url-poll-interval-seconds: 5
    fetch-registry: true
    serviceUrl:
      # Use the SERVICE NAME from your docker-compose file
      defaultZone: http://service-registry:8762/eureka/
  instance:
    # Highly recommended for Docker environments
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:12cb2175f8b3b3c1c20bab54b3a300444246a3f692c3ae546789bc5cb7d86365bdf7913edde5ba7827a18b3eeca27233ae36320487d5357bdd9394d7abac0d8c}          # min 64-char random string in env var
  access-token-expiry-ms: 900000       # 15 minutes
  refresh-token-expiry-ms: 2592000000  # 30 days